### PR TITLE
Use lists:keyfind/3

### PR DESCRIPTION
**Pull request by saa**

### CODE REVIEW

**Comment by artemeff** [comment]
Thanks!

**Comment by artemeff** [comment]
But, what if we don't have a value? It throws exception about wrong matching, instead of undefined or something else.

**Comment by saa** [comment]
You right. My mistake. Create new pull request or you make commit?

**Comment by artemeff** [comment]
Make your own, please :)

**Comment by saa** [comment]
Ok, np.

**Pull request merged**
